name: on_chain_swap
description: This package enables seamless interaction with the Chainflip network and supports Ethereum, Bitcoin, Solana and substrate, facilitating cross-chain swaps without dependencies.
version: 0.1.0
homepage: "https://github.com/mrtnetwork/onchain_swap"
repository: "https://github.com/mrtnetwork/onchain_swap"
Author: mrhaydari.t@gmail.com
topics:
  - chainflip
  - ethereum
  - substrate
  - solana
  - bitcoin
  
environment:
  sdk: '>=3.6.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  bitcoin_base:
    path: ../bitcoin_base
  blockchain_utils: ^5.1.0
  cosmos_sdk:
    path: ../cosmos_sdk
  on_chain:
    path: ../On_chain
  polkadot_dart:
    path: ../polkadot_dart
  # blockchain_utils:
  #   path: ../blockchain_utils
dev_dependencies:
  test: ^1.25.8
  lints: ^4.0.0
  flutter_lints: ^4.0.0