name: on_chain_swap
description: This package enables seamless interaction with the Chainflip network and supports Ethereum, Bitcoin, Solana and substrate, facilitating cross-chain swaps without dependencies.
version: 0.1.0
homepage: "https://github.com/mrtnetwork/onchain_swap"
repository: "https://github.com/mrtnetwork/onchain_swap"
Author: mrhaydari.t@gmail.com
topics:
  - chainflip
  - ethereum
  - substrate
  - solana
  - bitcoin
  
environment:
  sdk: '>=3.6.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  blockchain_utils: ^5.1.0
  cosmos_sdk: ^2.8.0
  on_chain: ^6.8.0
  bitcoin_base: ^6.6.0
  polkadot_dart: ^3.9.0
dev_dependencies:
  test: ^1.25.8
  lints: ^4.0.0
  flutter_lints: ^4.0.0